name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --experimental-vm-modules
    steps:
      - uses: actions/checkout@v2
      - name: Change to parent directory
        run: cd ..
      - name: Install supertest
        working-directory: server
        run: npm install supertest
      - name: Run tests
        run: npx jest --verbose


