name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: .\Server\app.test.js
        with:
          node-version: '14'
      - run: npm install
      - run: NODE_OPTIONS=--experimental-vm-modules npx jest
