name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Install supertest
        run: npm install supertest
        working-directory: Server
      - name: Run tests
        env:
          NODE_OPTIONS: --experimental-vm-modules
        run: timeout 1s npx jest

